[package]
name = "tic_tac_toe"
version = "0.9.0"
edition = "2018"
authors = ["Ahmad Amr Siam<ahmad.siam.coder@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
